name: DownloaderAction
on:
  repository_dispatch:
    types:
      - downloaderaction-ipfs

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create directory
        shell: bash
        run: mkdir -p download
      - name: Masking Secrets
        shell: bash
        run: |
          echo -n '::add-mask::' >> secrets.txt && \
          jq -r .client_payload.link < "${GITHUB_EVENT_PATH}" >> secrets.txt && \
          echo -n '::add-mask::' >> secrets.txt && \
          jq -r .client_payload.channel < "${GITHUB_EVENT_PATH}" >> secrets.txt && \
          echo -n '::add-mask::' >> secrets.txt && \
          jq -r .client_payload.message < "${GITHUB_EVENT_PATH}" >> secrets.txt && \
          cat secrets.txt && \
          rm -rf secrets.txt
      - name: Start Tor Proxy
        shell: bash
        run: |
          docker run -it -d \
            -p 8118:8118 \
            -p 9050:9050 \
            --name tor-proxy \
            dperson/torproxy:latest && \
          sleep 20
      - name: Confirmation of link survival
        id: link_status
        shell: bash
        run: |
          if [[ ${{ toJSON(github.event.client_payload.link) }} =~ ^http.*$ ]]; then
            retry=0
            flag=false
            status=""
            until "${flag}" || (( "${retry}" == 1000 )); do
              status="$(curl -siL -m 18000 --retry 100 --retry-all-errors -x http://localhost:8118 ${{ toJSON(github.event.client_payload.link) }} -o /dev/null -w '%{http_code}\n';:)" && \
              flag=true
              if "${flag}"; then
                :
              else
                ((retry++)) || true
              fi
            done
            if [[ "${status}" != "200" && "${status}" != "302" && "${status}" != "307" ]]; then
              status="notfound" && \
              echo "status=${status}" >> "${GITHUB_OUTPUT}" && \
              exit 2
            fi
          fi
      - name: Start Downloader Action
        if: ${{ success() }}
        timeout-minutes: 300
        shell: bash
        run: |
          port=$(echo {6881..6999} | tr ' ' \\n | shuf -n1)
          cd download && \
          docker run --rm -i \
            -p ${port}:${port} \
            -p ${port}:${port}/udp \
            -v $(pwd):/download \
            --link tor-proxy:tor \
            redpeacock78/downloaderaction:latest \
            -s20 -j20 -x16 -k20M \
            --all-proxy="http://tor:8118" \
            --listen-port=${port} \
            --dht-listen-port=${port} \
            --seed-time=0 \
            --max-tries=0 \
            --retry-wait=10 \
            --summary-interval=0 \
            --download-result=hide \
            --console-log-level=error \
            ${{ toJSON(github.event.client_payload.link) }}
      - name: Upload files to ipfs
        if: ${{ success() }}
        id: anonfiles
        shell: bash
        run: |
          cd download && \
          json="$(curl -s -x http://localhost:8118 -X POST -F file=@"$(ls)" ${{ secrets.IPFS_API }})" && \
          name="$(jq -r .Name <<<"${json}")" && \
          hash="$(jq -r .Hash <<<"${json}")" && \
          size="$(jq -r .Size <<<"${json}")"
          echo "::add-mask::${hash}" && \
          echo "::add-mask::${name}" && \
          echo "::add-mask::${size}" && \
          echo "hash=${hash}" >> "${GITHUB_OUTPUT}" && \
          echo "name=${name}" >> "${GITHUB_OUTPUT}" && \
          echo "size=${size}" >> "${GITHUB_OUTPUT}"
      - name: Check Content
        if: ${{ success() }}
        shell: bash
        run: |
          retry=0
          flag=false
          until "${flag}" || (( "${retry}" == 1000 )); do
            echo "Retry count: ${retry}"
            echo "Flag status: ${flag}"
            curl -sL \
              -m 18000 \
              --retry 100 \
              --retry-all-errors \
              --output /dev/null \
              "${{ secrets.IPFS_GATEWAY }}${{ steps.anonfiles.outputs.hash }}" && \
              flag=true
              if "${flag}"; then
              :
            else
              ((retry++)) || true
            fi
            sleep 1
          done
      - name: All succeeded
        if: ${{ success() }}
        shell: bash
        run: |
          cd download && \
          type="$(file "${{ steps.anonfiles.outputs.name }}" | awk -F : '{sub(/^ /,"",$2);print $2}')" && \
          link="${{ secrets.IPFS_GATEWAY }}${{ steps.anonfiles.outputs.hash }}" && \
          curl -s -X POST \
            ${{ secrets.ENDPOINT_URL }} \
            -H "Accept: application/json" \
            -H "Content-type: application/json" \
            -d @- <<EOF
          {
            "status": "success",
            "channel": ${{ toJSON(github.event.client_payload.channel) }},
            "message": ${{ toJSON(github.event.client_payload.message) }},
            "title": "${{ steps.anonfiles.outputs.name }}",
            "size": "${{ steps.anonfiles.outputs.size }}",
            "type": "${type}",
            "link": "${link}",
            "origin_link": ${{ toJSON(github.event.client_payload.link) }}
          }
          EOF
      - name: Download file not found
        if: >-
          ${{
            failure() &&
            steps.link_status.outputs.status != ''
          }}
        shell: bash
        run: |
          curl -s -X POST \
            ${{ secrets.ENDPOINT_URL }} \
            -H "Accept: application/json" \
            -H "Content-type: application/json" \
            -d @- <<EOF
          {
            "status": "failure",
            "channel": ${{ toJSON(github.event.client_payload.channel) }},
            "message": ${{ toJSON(github.event.client_payload.message) }},
            "link": ${{ toJSON(github.event.client_payload.link) }},
            "content": "Sorry! This link has expired."
          }
          EOF
      - name: Download timed out
        if: >-
          ${{
            failure() &&
            steps.link_status.outputs.status == ''
          }}
        shell: bash
        run: |
          curl -s -X POST \
            ${{ secrets.ENDPOINT_URL }} \
            -H "Accept: application/json" \
            -H "Content-type: application/json" \
            -d @- <<EOF
          {
            "status": "failure",
            "channel": ${{ toJSON(github.event.client_payload.channel) }},
            "message": ${{ toJSON(github.event.client_payload.message) }},
            "link": ${{ toJSON(github.event.client_payload.link) }},
            "content": "Sorry! Processing time exceeded 5 hours and timed out."
          }
          EOF
