name: DownloaderAction
on:
  repository_dispatch:
    types:
      - downloaderaction

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make Directory
        shell: bash
        run: mkdir -p download
      - name: Docker Run
        shell: bash
        run: |
          cd download && \
          docker run --rm -i \
            -p 6988:6988 \
            -p 6982:6982/udp \
            -v $(pwd):/download \
            redpeacock78/downloaderaction:latest \
            ${{ toJSON(github.event.client_payload.link) }}
      - name: Upload
        id: anonfiles
        shell: bash
        run: |
          cd download && \
          file="$(ls)" && \
          json="$(curl -s -F "file=@${file}" https://api.anonfiles.com/upload)" && \
          echo "::set-output name=json::${json}"
      - name: Result
        shell: bash
        run: |
          echo "https://anonfiles-api.vercel.app/${{ fromJson(steps.anonfiles.outputs.json).data.file.metadata.id }}/${{ fromJson(steps.anonfiles.outputs.json).data.file.metadata.name }}"
