name: DownloaderAction
on:
  repository_dispatch:
    types:
      - downloaderaction

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Create directory
        shell: bash
        run: mkdir -p download
      - name: Masking Secrets
        shell: bash
        run: |
          echo -n '::add-mask::' >> secrets.txt && \
          jq -r .client_payload.link < "${GITHUB_EVENT_PATH}" >> secrets.txt && \
          echo -n '::add-mask::' >> secrets.txt && \
          jq -r .client_payload.channel < "${GITHUB_EVENT_PATH}" >> secrets.txt && \
          echo -n '::add-mask::' >> secrets.txt && \
          jq -r .client_payload.message < "${GITHUB_EVENT_PATH}" >> secrets.txt && \
          cat secrets.txt && \
          rm -rf secrets.txt
      - name: Start Tor Proxy
        shell: bash
        run: |
          docker run -it -d \
            -p 8118:8118 \
            -p 9050:9050 \
            --name tor-proxy \
            dperson/torproxy:latest && \
          sleep 20
      - name: Confirmation of link survival
        id: link_status
        shell: bash
        run: |
          if [[ ${{ toJSON(github.event.client_payload.link) }} =~ ^http.*$ ]]; then
            status="$(curl -siL -x http://localhost:8118 ${{ toJSON(github.event.client_payload.link) }} -o /dev/null -w '%{http_code}\n')"
            if [[ "${status}" != "200" ]]; then
              status="notfound" && \
              echo "status=${status}" >> "$GITHUB_OUTPUT" && \
              exit 2
            fi
          fi
      - name: Make dht.dat
        if: ${{ success() }}
        id: make_dht
        shell: bash
        run: |
          hex=""
          hex+="a1 a2"
          hex+="02"
          hex+="00 00 00"
          hex+="00 03"
          hex+=$(printf "%016x\n" $(date --utc +%s))
          hex+="00 00 00 00 00 00 00 00"
          hex+=$(dd if=/dev/random bs=1 count=40 status=none | sha1sum - | cut -c1-40)
          hex+="00 00 00 00"
          hex+="00 00 00 00"
          hex+="00 00 00 00"
          echo ${hex} | xxd -r -p > dht.dat && \
          echo "dht_path=$(pwd)" >> "$GITHUB_OUTPUT"
      - name: Datermine the port numer to use
        if: ${{ success() }}
        id: use_port
        shell: bash
        run: |
          echo "number=$(echo {1024..65535} | tr ' ' \\n | shuf -n1)" >> "$GITHUB_OUTPUT"
      - name: Start Docker
        if: ${{ success() }}
        timeout-minutes: 300
        shell: bash
        run: |
          port=$(echo {6881..6999} | tr ' ' \\n | shuf -n1)
          cd download && \
          docker run --rm -i \
            -p ${{ steps.use_port.outputs.number }}:${{ steps.use_port.outputs.number }} \
            -p ${{ steps.use_port.outputs.number }}:${{ steps.use_port.outputs.number }}/udp \
            -v $(pwd):/download \
            -v ${{ steps.make_dht.outputs.dht_path }}:/root/.cache/aria2 \
            --link tor-proxy:tor \
            redpeacock78/downloaderaction:latest \
            -s20 -j20 -x16 -k20M \
            --all-proxy="http://tor:8118" \
            --listen-port=${{ steps.use_port.outputs.number }} \
            --dht-listen-port=${{ steps.use_port.outputs.number }} \
            --disable-ipv6=true \
            --continue=true \
            --seed-time=0 \
            --max-tries=0 \
            --retry-wait=10 \
            --summary-interval=0 \
            --download-result=hide \
            --console-log-level=error \
            ${{ toJSON(github.event.client_payload.link) }}
      - name: Upload files to anonfiles
        if: ${{ success() }}
        id: anonfiles
        shell: bash
        run: |
          cd download && \
          file="$(ls)" && \
          json="$(curl -s -x http://localhost:8118 -F "file=@${file}" https://api.anonfiles.com/upload)" && \
          id="$(jq -r .data.file.metadata.id <<<"${json}")" && \
          name="$(jq -r .data.file.metadata.name <<<"${json}")" && \
          size="$(jq -r .data.file.metadata.size.readable <<<"${json}")"
          echo "::add-mask::${id}" && \
          echo "::add-mask::${name}" && \
          echo "::add-mask::${size}" && \
          echo "id=${id}" >> "$GITHUB_OUTPUT" && \
          echo "name=${name}" >> "$GITHUB_OUTPUT" && \
          echo "size=${size}" >> "$GITHUB_OUTPUT"
      - name: All succeeded
        if: ${{ success() }}
        shell: bash
        run: |
          cd download && \
          type="$(file "${{ steps.anonfiles.outputs.name }}"|awk -F : '{sub(/^ /,"",$2);print $2}')" && \
          link="$(node -e "console.log(encodeURI('https://anonfiles-api.vercel.app/${{ steps.anonfiles.outputs.id }}/${{ steps.anonfiles.outputs.name }}'))")" && \
          curl -s -X POST \
            ${{ secrets.ENDPOINT_URL }} \
            -H "Accept: application/json" \
            -H "Content-type: application/json" \
            -d @- <<EOF
          {
            "status": "success",
            "channel": ${{ toJSON(github.event.client_payload.channel) }},
            "message": ${{ toJSON(github.event.client_payload.message) }},
            "title": "${{ steps.anonfiles.outputs.name }}",
            "size": "${{ steps.anonfiles.outputs.size }}",
            "type": "${type}",
            "link": "${link}",
            "origin_link": ${{ toJSON(github.event.client_payload.link) }}
          }
          EOF
      - name: Download file not found
        if: >-
          ${{
            failure() &&
            steps.link_status.outputs.status != ''
          }}
        shell: bash
        run: |
          curl -s -X POST \
            ${{ secrets.ENDPOINT_URL }} \
            -H "Accept: application/json" \
            -H "Content-type: application/json" \
            -d @- <<EOF
          {
            "status": "failure",
            "channel": ${{ toJSON(github.event.client_payload.channel) }},
            "message": ${{ toJSON(github.event.client_payload.message) }},
            "link": ${{ toJSON(github.event.client_payload.link) }},
            "content": "Sorry! This link has expired."
          }
          EOF
      - name: Download timed out
        if: >-
          ${{
            failure() &&
            steps.link_status.outputs.status == ''
          }}
        shell: bash
        run: |
          curl -s -X POST \
            ${{ secrets.ENDPOINT_URL }} \
            -H "Accept: application/json" \
            -H "Content-type: application/json" \
            -d @- <<EOF
          {
            "status": "failure",
            "channel": ${{ toJSON(github.event.client_payload.channel) }},
            "message": ${{ toJSON(github.event.client_payload.message) }},
            "link": ${{ toJSON(github.event.client_payload.link) }},
            "content": "Sorry! Processing time exceeded 5 hours and timed out."
          }
          EOF
