name: DownloaderAction
on:
  repository_dispatch:
    types:
      - downloaderaction

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Create directory
        shell: bash
        run: mkdir -p download
      - name: Mask secret
        shell: bash
        run: |
          echo -n '::add-mask::' >> secrets.txt && \
          jq < "${GITHUB_EVENT_PATH}" -r .client_payload.link >> secrets.txt && \
          echo -n '::add-mask::' >> secrets.txt && \
          jq < "${GITHUB_EVENT_PATH}" -r .client_payload.channel >> secrets.txt && \
          echo -n '::add-mask::' >> secrets.txt && \
          jq < "${GITHUB_EVENT_PATH}" -r .client_payload.message >> secrets.txt && \
          cat secrets.txt && \
          rm -rf secrets.txt
      - name: Confirmation of link survival
        id: link_status
        shell: bash
        run: |
          if [[ ${{ toJSON(github.event.client_payload.link) }} =~ ^http.*$ ]]; then
            status="$(curl -siL ${{ toJSON(github.event.client_payload.link) }} -o /dev/null -w '%{http_code}\n')"
            if [[ "${status}" != "200" ]]; then
              status="notfound" && \
              echo "::set-output name=status::${status}" && \
              exit 2
            fi
          fi
      - name: Start Docker
        if: ${{ success() }}
        timeout-minutes: 300
        shell: bash
        run: |
          cd download && \
          docker run --rm -i \
            -p 6988:6988 \
            -p 6982:6982/udp \
            -v $(pwd):/download \
            redpeacock78/downloaderaction:latest \
            ${{ toJSON(github.event.client_payload.link) }}
      - name: Upload files to anonfiles
        if: ${{ success() }}
        id: anonfiles
        shell: bash
        run: |
          cd download && \
          file="$(ls)" && \
          json="$(curl -s -F "file=@${file}" https://api.anonfiles.com/upload)" && \
          id="$(jq < "${json}" -r .data.file.metadata.id)" && \
          name="$(jq < "${json}" -r .data.file.metadata.name)" && \
          echo "::add-mask::${id}" && \
          echo "::add-mask::${name}" && \
          echo "::set-output name=id::${id}" && \
          echo "::set-output name=file::${name}"
      - name: "If successful: Access callback URL"
        if: ${{ success() }}
        shell: bash
        run: |
          cd download && \
          size="$(ls -lh|awk '{print $5}')" && \
          type="$(file "${file}"|awk -F : '{sub(/^ /,"",$2);print $2}')" && \
          link="$(node -e "console.log(encodeURI('https://anonfiles-api.vercel.app/${{ steps.anonfiles.outputs.id }}/${{ steps.anonfiles.outputs.name }}'))")" && \
          curl -s -X POST \
            ${{ secrets.ENDPOINT_URL }} \
            -H "Accept: application/json" \
            -H "Content-type: application/json" \
            -d @- <<EOF
          {
            "status": "success",
            "channel": ${{ toJSON(github.event.client_payload.channel) }},
            "message": ${{ toJSON(github.event.client_payload.message) }},
            "title": "${{ steps.anonfiles.outputs.name }}",
            "size": "${size}",
            "type": "${type}",
            "link": "${link}"
          }
          EOF
      - name: Not Found
        if: >-
          ${{
            failure() &&
            steps.link_status.outputs.status != ''
          }}
        shell: bash
        run: |
          curl -s -X POST \
            ${{ secrets.ENDPOINT_URL }} \
            -H "Accept: application/json" \
            -H "Content-type: application/json" \
            -d @- <<EOF
          {
            "status": "failure",
            "channel": ${{ toJSON(github.event.client_payload.channel) }},
            "message": ${{ toJSON(github.event.client_payload.message) }},
            "link": ${{ toJSON(github.event.client_payload.link) }},
            "content": "Sorry! This link has expired."
          }
          EOF
      - name: Time Out
        if: >-
          ${{
            failure() &&
            steps.link_status.outputs.status == ''
          }}
        shell: bash
        run: |
          curl -s -X POST \
            ${{ secrets.ENDPOINT_URL }} \
            -H "Accept: application/json" \
            -H "Content-type: application/json" \
            -d @- <<EOF
          {
            "status": "failure",
            "channel": ${{ toJSON(github.event.client_payload.channel) }},
            "message": ${{ toJSON(github.event.client_payload.message) }},
            "link": ${{ toJSON(github.event.client_payload.link) }},
            "content": "Sorry! Processing time exceeded 5 hours and timed out."
          }
          EOF
